services:
  - type: web
    name: book-jonflow-mdq
    runtime: node
    plan: free
    region: frankfurt
    rootDir: relay
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SYMBOL
        value: btcusdt
      - key: BUCKET_SIZE
        value: "5"
      - key: RANGO_BUCKETS
        value: "220"
      - key: INTERVALO_ENVIO_MS
        value: "250"
      - key: MODO_DEMO
        value: "0"
      - key: GEX_INTERVALO_MS
        value: "60000"
      - key: MARGEN_RECENTRADO_USD
        value: "700"
    healthCheckPath: /salud
